version: "3.9"
services:
  deploy:
    container_name: java14app2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://walletDemo:5432/wallet_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      java14-network:
        aliases:
          - java14app
    volumes:
      - ./target:/opt/app
    restart: unless-stopped
networks:
  java14-network:
    name: 'our_java14_network'